# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Industry', '0001_initial'),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='دانشگاه/مدرسه')),
                ('degree', models.CharField(choices=[('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=30, verbose_name='مدرک تحصیلی')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='نمره یا معدل')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'حرفه\u200cای')], max_length=20, verbose_name='سطح مهارت')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('contractual', 'قراردادی')], max_length=20, verbose_name='نوع استخدام')),
                ('title', models.CharField(help_text='عنوان شغلی یا نقش در این تجربه', max_length=255, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=255, verbose_name='شرکت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_locations', to='Locations.city', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'تجربه کاری',
                'verbose_name_plural': 'تجربیات کاری',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, null=True, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=20, null=True, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('Completed', 'پایان خدمت'), ('Permanent Exemption', 'معافیت دائم'), ('Educational Exemption', 'معافیت تحصیلی'), ('Not Completed', 'نااتمام')], max_length=30, null=True, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('Below Diploma', 'زیر دیپلم'), ('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=20, null=True, verbose_name='مدرک تحصیلی')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='سال سابقه مرتبط')),
                ('experience', models.CharField(choices=[('No EXPERIENCE', 'بدون سابقه کار'), ('Less than Three', 'کمتر از 3 سال'), ('Three or More', '3 تا 6 سال'), ('Six or More', 'بیشتر از 6 سال')], max_length=50, null=True, verbose_name='سابقه کاری')),
                ('expected_salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=20, null=True, verbose_name='حقوق مورد نظر')),
                ('preferred_job_type', models.CharField(choices=[('Full-Time', 'تمام وقت'), ('Part-Time', 'پاره وقت'), ('Remote', 'دورکاری'), ('Internship', 'کارآموزی')], max_length=20, null=True, verbose_name='نوع شغل مورد علاقه')),
                ('cv', models.FileField(null=True, upload_to='jobseekers/resumes/', verbose_name='رزومه')),
                ('availability', models.CharField(choices=[('immediately', 'فوری'), ('with_notice', 'با اطلاع'), ('not_available', 'غیرقابل دسترسی')], default='immediately', max_length=20, null=True, verbose_name='وضعیت دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_industry', to='Industry.industry', verbose_name='صنعت')),
            ],
        ),
    ]
