# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Industry', '0001_initial'),
        ('Locations', '0001_initial'),
        ('Resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerresume',
            name='job_seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='جوینده کار'),
        ),
        migrations.AddField(
            model_name='jobseekerresume',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experiences', to='Resumes.jobseekerresume', verbose_name='رزومه'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Educations', to='Resumes.jobseekerresume', verbose_name='رزومه'),
        ),
        migrations.AddField(
            model_name='jobseekerskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Seeker_Skills', to='Resumes.jobseekerresume', verbose_name='رزومه'),
        ),
        migrations.AddField(
            model_name='jobseekerskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Job_Seeker', to='Industry.skill', verbose_name='مهارت'),
        ),
    ]
