# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertisements', '0001_initial'),
        ('Companies', '0001_initial'),
        ('Industry', '0001_initial'),
        ('Locations', '0001_initial'),
        ('Resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resumes.jobseekerresume'),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='advertisement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisement', to='Advertisements.advertisement', verbose_name='آگهی'),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_advertisements', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisements_industry', to='Industry.industry', verbose_name='صنعت'),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisements_location', to='Locations.city', verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='application',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Advertisements.jobadvertisement'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='advertisement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisement', to='Advertisements.advertisement', verbose_name='آگهی'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements_industry', to='Industry.industry', verbose_name='صنعت'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل کارجو'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements_location', to='Locations.city', verbose_name='موقعیت'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume', to='Resumes.jobseekerresume', verbose_name='رزومه'),
        ),
    ]
