# Generated by Django 5.1.7 on 2025-06-09 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام شرکت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='لوگو')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='بنر')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='ویدئوی معرفی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
                ('number_of_employees', models.IntegerField(blank=True, null=True, verbose_name='تعداد کارکنان')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لینک Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
    ]
