# Generated by Django 5.1.7 on 2025-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل مدیر',
                'verbose_name_plural': 'پروفایل\u200cهای مدیران',
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره شرکت یا اهداف', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employers/profile_pics/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل کارفرما',
                'verbose_name_plural': 'پروفایل\u200cهای کارفرمایان',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='عنوان شغلی کوتاه (الزامی)', max_length=255, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='jobseekers/profile_pics/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل جوینده کار',
                'verbose_name_plural': 'پروفایل\u200cهای جویندگان کار',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], default='M', max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('kids_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فرزند')),
            ],
            options={
                'verbose_name': 'اطلاعات شخصی',
                'verbose_name_plural': 'اطلاعات شخصی',
            },
        ),
        migrations.CreateModel(
            name='SupportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل\u200cهای پشتیبان',
            },
        ),
    ]
