# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دسته\u200cبندی گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات دسته\u200cبندی')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'در انتظار'), ('RE', 'حل شده'), ('RJ', 'رد شده')], default='PE', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_reports', to='Advertisements.advertisement', verbose_name='آگهی گزارش شده')),
            ],
        ),
    ]
