# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('ad_type', models.CharField(choices=[('J', 'شغل'), ('R', 'رزومه')], max_length=1, verbose_name='نوع آگهی')),
                ('durations', models.IntegerField(default=1, verbose_name='مدت زمان اشتراک')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('total_price', models.IntegerField(verbose_name='قیمت نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_orders', to='Advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'سفارش آگهی',
                'verbose_name_plural': 'سفارشات آگهی ها',
            },
        ),
    ]
