# Generated by Django 5.1.7 on 2025-07-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0002_initial'),
        ('Orders', '0002_initial'),
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='pending_job_data',
            field=models.JSONField(blank=True, help_text='اطلاعات آگهی که قبل از پرداخت ذخیره می\u200cشود', null=True, verbose_name='اطلاعات موقت آگهی'),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_orders', to='Advertisements.advertisement'),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک آگهی ها'),
        ),
    ]
