# Generated by Django 5.1.7 on 2025-06-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='userregisterotp',
            name='otp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='Authentication.onetimepassword', verbose_name='ارجاع رمز یکبار مصرف'),
        ),
    ]
